name: Review patternmain documentation

on:
  pull_request:
    branches:
      - master

jobs:
  run-patpatbot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run PatPatBot Action
      uses: nicklem/patpatbot@main
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        REPO_NAME: ${{ github.event.repository.name }}
        INPUT_DOCS_GLOB: ${{ github.event.inputs.directory || 'docs/description/*.md' }}
